on: [push, pull_request]

name: test
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Install code check tools
        run: |
          pip install pre-commit
          go install golang.org/x/tools/cmd/goimports@latest
          go install golang.org/x/lint/golint@latest
          go install github.com/fzipp/gocyclo/cmd/gocyclo@latest

      - name: Code checks
        run: pre-commit run --all-files

  test:
    strategy:
      fail-fast: false
      matrix:
        go-version:
          - 1.17.x
          - 1.18.x
          - 1.19.x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: |
          go build ./...

      - name: Test
        run: >
          go test -race
          -coverprofile=coverage.txt
          -coverpkg=all
          -covermode=atomic
          ./...

      - uses: codecov/codecov-action@v3
        if: ${{ matrix.go-version == '1.19.x' }}
