on: [push, pull_request]

name: test
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19.x

      - name: install code check tools
        run: |
          go get -u golang.org/x/lint/golint
          go get -u github.com/fzipp/gocyclo/cmd/gocyclo
          # do not change go.mod and go.sum
          git checkout go.mod go.sum

      - name: code checks
        uses: pre-commit/action@v2.0.0
        with:
          extra_args: --all-files

  test:
    strategy:
      matrix:
        go-version:
          - 1.13.x
          - 1.14.x
          - 1.15.x
          - 1.16.x
          - 1.17.x
          - 1.18.x
          - 1.19.x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: build
        run: |
          go build ./...

      - name: test
        run: |
          go test -v -coverprofile=coverage.txt -coverpkg=all -covermode=atomic ./...
          (bash <(curl -s https://codecov.io/bash))> /dev/null
